import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <h1 className="rexr-2xl text-center my-6 font-semibold">Welcome to Next.js Starwars Website</h1> 
      <p className="mb-5">Lucas’s success as a writer and director with American Graffiti (1973) gained him the backing of 20th Century Fox, which put up $9.5 million for the production of the first Star Wars film. The film, directed by Lucas, was in production for four years, with scenes shot in Tunisia and Death Valley, California, and on soundstages in England. When it was released on May 25, 1977, Star Wars (later retitled Star Wars: Episode IV—A New Hope) met with runaway success. A space opera set “a long time ago in a galaxy far, far away,” the film centres on Luke Skywalker (played by the then relatively unknown Mark Hamill), a young man who finds himself embroiled in an interplanetary war between an authoritarian empire and rebel forces.</p> 
       <p className="mb-5" >Skywalker and the opportunistic smuggler Han Solo (Harrison Ford) are tasked with saving Princess Leia (Carrie Fisher) from captivity on a massive space station commanded by the menacing Darth Vader, whose deep mechanically augmented voice (contributed by James Earl Jones) became instantly iconic. At the core of the film and the series it initiated are the Jedi Knights—a group of either benevolent or malevolent warriors who harness and manipulate the Force, an all-pervasive spiritual essence that holds in balance the forces of good and evil—and Skywalker’s quest to join their ranks.</p> 
        <p className="mb-5">Though Star Wars initially opened in only 42 theatres, the film earned almost $3 million in its first week and had grossed $100 million by the end of the summer. The film won six Academy Awards along with a special-achievement award for accomplishments in sound, and it revolutionized the motion picture industry with its advancements in special effects. Lucas’s effects company, Industrial Light and Magic (ILM), designed a slew of imaginative alien creatures and mechanical “droids” that populated a variety of exotic locales. Perhaps most impressive, however, were the elaborate space battles accomplished with scaled miniatures. The series continued to make remarkable advancements in the field of special effects into the 21st century, and ILM became one of the most successful effects studios utilized by Hollywood. Lucas followed the first Star Wars film with two sequels, Star Wars: Episode V—The Empire Strikes Back (1980) and Star Wars: Episode VI—Return of the Jedi (1983). The franchise thrived in the 1980s and ’90s through the release of videos, a substantial merchandise line, and the theatrical re-release of the trilogy in 1997.</p> 
        <p className="mb-5">Twentieth Centuryx-Fox
        monster being created for Star Wars: Episode VI—Return of the Jedi
        monster being created for Star Wars: Episode VI—Return of the Jedi
        Model maker for Industrial Light and Magic working on a monster for Star Wars: Episode VI—Return of the Jedi (1983).
        © 1983 Lucasfilm Ltd. & TM. All rights reserved.
        scene from Star Wars: Episode V—The Empire Strikes Back
        scene from Star Wars: Episode V—The Empire Strikes Back
        (From left): Peter Mayhew (Chewbacca), Anthony Daniels (C-3PO), Carrie Fisher (Princess Leia), and Harrison Ford (Han Solo) in Star Wars: Episode V—The Empire Strikes Back (1980), directed by Irvin Kershner.
        Twentieth Century-Fox
        More than 20 years after the first film appeared, Lucas began releasing a second trilogy of films depicting events that had transpired before those in the original series. Lucas returned to the role of director (he had directed the first film but not its two sequels) and utilized a new cast of popular young actors—including Ewan McGregor and Natalie Portman—as well as recent advancements in digital video technology. Star Wars: Episode I—The Phantom Menace (1999), Star Wars: Episode II—Attack of the Clones (2002), and Star Wars: Episode III—Revenge of the Sith (2005) were all box-office successes, though they received markedly less critical acclaim than the original trilogy. The Star Wars franchise, however, remained incredibly lucrative into the 21st century. It included not only clothing, action figures, and multiple extensive book series but also the animated feature film Star Wars: The Clone Wars (2008)—which depicted events occurring between Episode II and Episode III—and numerous successful video game lines created by another of Lucas’s companies, LucasArts. By the time the sixth film was released in 2005, nearly 30 years after the series began, it was estimated that the franchise as a whole had brought in some $20 billion, an achievement thus far unparalleled in the motion picture industry.</p> 
        <p className="mb-5">https://www.britannica.com/topic/Star-Wars-film-series</p>
    </div>
  )
}
